# Generated by Django 2.2.19 on 2021-03-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='who',
            field=models.CharField(blank=True, default='Internal Event', help_text='Name of Organization', max_length=120),
        ),
    ]
