# Generated by Django 2.2.19 on 2021-03-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
