# Generated by Django 2.2.19 on 2021-03-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
        migrations.RenameModel(
            old_name='Spaces',
            new_name='Space',
        ),
    ]
