# Generated by Django 2.2.19 on 2021-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210319_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='facilitator',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
