# Generated by Django 2.2.19 on 2021-03-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_program_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
