# Generated by Django 2.2.19 on 2021-03-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_program_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, default='About Space'),
        ),
    ]
