# Generated by Django 2.2.19 on 2021-03-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_space_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='classtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
