# Generated by Django 2.2.19 on 2021-03-26 18:17

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_program_classtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='team_member',
        ),
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.upload_image_path),
        ),
    ]
