# Generated by Django 2.2.19 on 2021-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210326_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
