# Generated by Django 2.2.19 on 2021-03-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_contact', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=120)),
                ('business_name', models.CharField(blank=True, default='iSpace', help_text='Enter a business name if paticipant was a uwat or attended our program', max_length=120)),
                ('business_type', models.TextField(blank=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spaceusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=120)),
                ('business_reg_number', models.CharField(blank=True, max_length=120)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
