# Generated by Django 2.2.19 on 2021-03-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210319_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spaceuser',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
