# Generated by Django 2.2.19 on 2021-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_participant_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='spaceuser',
            name='team_member',
        ),
        migrations.AddField(
            model_name='spaceuser',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
