# Generated by Django 2.2.18 on 2021-04-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
    ]
