# Generated by Django 2.2.18 on 2021-04-04 20:27

from django.db import migrations, models
import finances.bookkeeper.sales


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20210404_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inoice_doc',
            field=models.FileField(blank=True, null=True, upload_to=finances.bookkeeper.sales.upload_image_path),
        ),
    ]
