# Generated by Django 2.2.18 on 2021-04-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_invoice_inoice_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='inoice_doc',
            new_name='invoice_doc',
        ),
    ]
