# Generated by Django 2.2.18 on 2021-04-04 21:06

from django.db import migrations, models
import finances.bookkeeper.accounting


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_invoice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('account', models.CharField(blank=True, choices=[('Cash on Hand', 'Cash on Hand'), ('Cash from Bank', 'Cash from Bank'), ('Cheque Payment', 'Cheque Payment'), ('Momo Transaction', 'Momo Transaction')], max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('doc', models.FileField(blank=True, null=True, upload_to=finances.bookkeeper.accounting.upload_image_path)),
            ],
        ),
    ]
