# Generated by Django 2.2.18 on 2021-04-04 21:34

from django.db import migrations, models
import finances.bookkeeper.purchases


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=39)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Ready', 'Ready'), ('Ready', 'Ready'), ('Ready', 'Ready')], default='Ready', max_length=120)),
                ('account', models.CharField(blank=True, choices=[('Cash on Hand', 'Cash on Hand'), ('Cash from Bank', 'Cash from Bank'), ('Cheque Payment', 'Cheque Payment'), ('Momo Transaction', 'Momo Transaction')], max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('doc', models.FileField(blank=True, null=True, upload_to=finances.bookkeeper.purchases.upload_image_path)),
            ],
        ),
    ]
