# Generated by Django 2.2.18 on 2021-04-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_auto_20210404_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_revenue',
            field=models.BooleanField(default=False),
        ),
    ]
