# Generated by Django 2.2.18 on 2021-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_auto_20210407_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('SALES', 'SALES'), ('INTERNET', 'INTERNET'), ('OFFICE SUPPLIES', 'OFFICE SUPPLIES'), ('PAYROLL', 'PAYROLL'), ('RENT', 'RENT'), ('REPAIRS', 'REPAIRS'), ('UTILITIES', 'UTILITIES')], max_length=120),
        ),
    ]
