# Generated by Django 2.2.18 on 2021-04-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_expense',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_revenue',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=120),
        ),
    ]
