# Generated by Django 2.2.18 on 2021-04-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_auto_20210407_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
