# Generated by Django 2.2.18 on 2021-04-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_merchant_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='item name', max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('bulk_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.CharField(blank=True, default='100 pieces', max_length=120, null=True)),
                ('quantity_remaining', models.IntegerField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(blank=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finances.Merchant')),
            ],
        ),
    ]
