# Generated by Django 2.2.18 on 2021-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_remaining',
            field=models.IntegerField(blank=True),
        ),
    ]
