# Generated by Django 2.2.19 on 2021-03-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_auto_20210319_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('on', models.DateTimeField(auto_now_add=True)),
                ('to', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='services.Space')),
            ],
        ),
    ]
