# Generated by Django 2.2.19 on 2021-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='internet_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='revenue_code',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
