# Generated by Django 2.2.18 on 2021-04-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='team_member',
        ),
    ]
